### ISSUE TITLE
Autofill Form Data

### ISSUE THREAD

**Issue by jamiezack** [eisenfox/foxholder#1]
No transitions on labels when the form is autofilled. 
<img width="624" alt="screen shot 2017-11-23 at 19 05 50" src="https://user-images.githubusercontent.com/33939703/33186414-5b393c8a-d081-11e7-88d6-0e29be6ff17b.png">

**Comment by eisenfox** [comment]
@jamiezack hey, trying to reproduce your bug and can't. Could you please give me a link to your website? I need to check a code a bit to fix this bug.

**Comment by jamiezack** [comment]
Hey, 

Firstly I forgot to add that this issue only exists when the form is auto-filled through https://www.pcapredict.com/

The page is unfortunately deep within a portal.  Can I send you the script/link privately as this screen is past a payment screen?

**Comment by eisenfox** [comment]
Files issues, can't check it - they even won't work =(

**Comment by jamiezack** [comment]
To pinpoint the issue, when the form element has the 'value' already pre-typed, the form overlaps like the above image
